.PHONY: all clean run

all:
	javac Juego.java Ball.java Sound.java Racquet.java Main.java GameMotion.java

clean:
	rm -f Juego.class Juego\$$1.class Ball.class Sound.class Racquet.class Main.class Main\$$1.class GameMotion.class